server {
    listen 80;

    # /app 요청을 app 컨테이너로 전달
    location /app/ {
        proxy_pass http://app/;
    }

    # 기본 요청은 nginx 기본 페이지
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
